### PR TITLE
Website redesign

### PR DESCRIPTION
**Pull request by captainexpo**
# Pull Request

## Description:

Updated styling for website.
Some temporary values still need to be filled in, and changes can still be made to the styling, layout, etc. (especially to the schedule part, I don't even know if it's necessary). 

An extremely simple 404 page was also added.

## Related Issue:

N/A

### CODE REVIEW

**Comment by jdogcoder** [comment]
SVG covered 
CleanShot 2024-03-12 at 17 58 02@2x

**Comment by jdogcoder** [comment]
other than that looks super good!

**Comment by jdogcoder** [comment]
Can we also add a team section?

**Review by jaspermayone — CHANGES_REQUESTED** [review]
see above comments

**Comment by Tiger-The-Cat** [comment]
This looks neat, here's some stuff I noticed:

- Sponsors section disappeared
- The drastic background change from blue to white really disrupts the "viewing experience", maybe just changing to a different shade of blue would accomplish your goal here?
- I love what you did with the schedule!
- The snow doesn't appear on top of the info cards
- On mobile: everything looks wonky:
image

**Comment by Captainexpo-1** [comment]
Should look better on mobile now, and added a team section (it needs to be written, and I don't have the brain power for that right now). Sponsor section is also back, and snow appears on top of the cards.

**Comment by jdogcoder** [comment]
Yay! Commenting out schedule and team for now so I can merge this and also added a simple reg button so we can finally get our grant.

**Review by jaspermayone — CHANGES_REQUESTED** [review]
CleanShot 2024-03-13 at 08 53 58@2x

**Review by jaspermayone — APPROVED** [review]
CleanShot 2024-03-13 at 09 52 12@2x

**Pull request merged**
